name: Simple Selenium CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create Maven project structure
        run: |
          mkdir -p src/main/java/com/example
          cd src/main/java/com/example
          cat > GoogleSearch.java <<'EOF'
          package com.example;

          import org.openqa.selenium.By;
          import org.openqa.selenium.WebDriver;
          import org.openqa.selenium.WebElement;
          import org.openqa.selenium.chrome.ChromeDriver;
          import org.openqa.selenium.chrome.ChromeOptions;
          import io.github.bonigarcia.wdm.WebDriverManager;

          public class GoogleSearch {
              public static void main(String[] args) throws Exception {
                  WebDriverManager.chromedriver().setup();
                  ChromeOptions options = new ChromeOptions();
                  options.addArguments("--headless");
                  WebDriver driver = new ChromeDriver(options);
                  driver.get("https://www.google.com");
                  WebElement box = driver.findElement(By.name("q"));
                  box.sendKeys("Selenium WebDriver");
                  box.submit();
                  Thread.sleep(2000);
                  System.out.println("Page title is: " + driver.getTitle());
                  driver.quit();
              }
          }
          EOF

      - name: Create Maven pom.xml
        run: |
          cat > pom.xml <<'EOF'
          <project xmlns="http://maven.apache.org/POM/4.0.0"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
            <modelVersion>4.0.0</modelVersion>
            <groupId>com.example</groupId>
            <artifactId>selenium-demo</artifactId>
            <version>1.0</version>
            <dependencies>
              <dependency>
                <groupId>org.seleniumhq.selenium</groupId>
                <artifactId>selenium-java</artifactId>
                <version>4.25.0</version>
              </dependency>
              <dependency>
                <groupId>io.github.bonigarcia</groupId>
                <artifactId>webdrivermanager</artifactId>
                <version>5.9.2</version>
              </dependency>
            </dependencies>
          </project>
          EOF

      - name: Build and Run Test
        run: |
          mvn -q compile exec:java -Dexec.mainClass="com.example.GoogleSearch"
